type sendInBlueEmail-head.html >> x.html
type sendInBlueEmail-cover.html >> x.html
type sendInBlueEmail-section1-row.html >> x.html
type sendInBlueEmail-section1-art1.html >> x.html
type sendInBlueEmail-section2-row.html >> x.html
type sendInBlueEmail-section2-art1.html >> x.html
type sendInBlueEmail-section2-art2.html >> x.html
type sendInBlueEmail-section2-art3.html >> x.html
type sendInBlueEmail-section2-art4.html >> x.html
type sendInBlueEmail-section2-art5.html >> x.html
type sendInBlueEmail-section2-art6.html >> x.html
type sendInBlueEmail-section2-art7.html >> x.html
type sendInBlueEmail-section2-art8.html >> x.html
type sendInBlueEmail-section3-row.html >> x.html
type sendInBlueEmail-section3-art1.html >> x.html
type sendInBlueEmail-section3-art2.html >> x.html
type sendInBlueEmail-section3-art3.html >> x.html
type sendInBlueEmail-section4-row.html >> x.html
type sendInBlueEmail-section4-art1.html >> x.html
type sendInBlueEmail-section4-art2.html >> x.html
type sendInBlueEmail-closing.html >> x.html
